Update __init__.py
This is to fix the following case:

In config.yam:
    art_filename: scan/front

Without these modifications, the `beet import` command fails: 

    Error: No such file or directory while copying /tmp/tmp5aczqcob.jpg to MY_DIR/ARTIST-ALBUM/scan/front.jpg

as generally (at least the way I'm using beets) the subdir 'scan' does not exist . 

With these modifications `beet import` will then create the missing subdir as needed, ditto `beet move` when moving. 

Please note that I'm no Python nor beets expert, so other/better fixes for this may exist. Please feel free to change or discard this PR if it is somehow innappropriate.